// 16 service categories × 4 sub-categories each
// Used for "Proposer un service" flow in CreateProviderProfile
export const SERVICE_CATEGORIES = [
  {
    id: 1,
    emoji: "🏥",
    slug: "salud",
    es: "Salud, Urgencias & Medicina",
    en: "Health, Emergencies & Medicine",
    color: "#EF4444",
    subcategories: [
      { id: "1a", es: "Medicina general, pediatría & urgencias a domicilio", en: "General medicine, pediatrics & home emergencies" },
      { id: "1b", es: "Especialidades médicas & odontología", en: "Medical specialties & dental care" },
      { id: "1c", es: "Farmacias, laboratorios & enfermeros", en: "Pharmacies, labs & nursing" },
      { id: "1d", es: "Diversos salud & cuidados médicos", en: "Various health & medical care" },
    ],
  },
  {
    id: 2,
    emoji: "🧠",
    slug: "bienestar-mental",
    es: "Bienestar Mental & Psicología",
    en: "Mental Wellness & Psychology",
    color: "#8B5CF6",
    subcategories: [
      { id: "2a", es: "Psicólogos clínicos & psicoterapeutas", en: "Clinical psychologists & psychotherapists" },
      { id: "2b", es: "Terapia de pareja & psicología infantil", en: "Couples therapy & child psychology" },
      { id: "2c", es: "Coaching de vida & desarrollo personal", en: "Life coaching & personal development" },
      { id: "2d", es: "Diversos salud mental & terapias", en: "Various mental health & therapies" },
    ],
  },
  {
    id: 3,
    emoji: "🌿",
    slug: "espiritualidad",
    es: "Espiritualidad, Chamanismo & Energía",
    en: "Spirituality, Shamanism & Energy",
    color: "#10B981",
    subcategories: [
      { id: "3a", es: "Chamanes tradicionales (Paqos), rituales & ofrendas", en: "Traditional shamans (Paqos), rituals & offerings" },
      { id: "3b", es: "Medicinas sagradas & centros de retiro", en: "Sacred medicines & retreat centers" },
      { id: "3c", es: "Terapias holísticas (Reiki, masajes, sonoterapia)", en: "Holistic therapies (Reiki, massage, sound healing)" },
      { id: "3d", es: "Diversos espiritualidad & misticismo andino", en: "Various spirituality & Andean mysticism" },
    ],
  },
  {
    id: 4,
    emoji: "🏋️",
    slug: "deportes",
    es: "Deportes, Fitness & Yoga",
    en: "Sports, Fitness & Yoga",
    color: "#F59E0B",
    subcategories: [
      { id: "4a", es: "Entrenadores personales & trail en altura", en: "Personal trainers & high-altitude trail" },
      { id: "4b", es: "Gimnasios, CrossFit & artes marciales", en: "Gyms, CrossFit & martial arts" },
      { id: "4c", es: "Yoga, Pilates & meditación", en: "Yoga, Pilates & meditation" },
      { id: "4d", es: "Diversos deporte, fitness & preparación física", en: "Various sport, fitness & physical training" },
    ],
  },
  {
    id: 5,
    emoji: "🚗",
    slug: "movilidad",
    es: "Movilidad, Choferes & Transporte",
    en: "Mobility, Drivers & Transport",
    color: "#3B82F6",
    subcategories: [
      { id: "5a", es: "Choferes privados (Cusco & Valle Sagrado)", en: "Private drivers (Cusco & Sacred Valley)" },
      { id: "5b", es: "Taxis de confianza, transfers aeropuerto & vans", en: "Trusted taxis, airport transfers & vans" },
      { id: "5c", es: "Alquiler de vehículos (autos, motos, bicicletas eléctricas)", en: "Vehicle rental (cars, motorcycles, e-bikes)" },
      { id: "5d", es: "Diversos transporte, carga & mudanzas", en: "Various transport, freight & moving" },
    ],
  },
  {
    id: 6,
    emoji: "🍽️",
    slug: "gastronomia",
    es: "Gastronomía, Chefs & Catering",
    en: "Gastronomy, Chefs & Catering",
    color: "#F97316",
    subcategories: [
      { id: "6a", es: "Chefs a domicilio & cocineros privados", en: "Home chefs & private cooks" },
      { id: "6b", es: "Catering, buffets & organización de banquetes", en: "Catering, buffets & banquet organization" },
      { id: "6c", es: "Cocineros de campamento (trekking & alta montaña)", en: "Camp cooks (trekking & high mountain)" },
      { id: "6d", es: "Diversos gastronomía, delivery & talleres culinarios", en: "Various gastronomy, delivery & culinary workshops" },
    ],
  },
  {
    id: 7,
    emoji: "🔧",
    slug: "reparaciones",
    es: "Reparaciones, Plomería & Construcción",
    en: "Repairs, Plumbing & Construction",
    color: "#6B7280",
    subcategories: [
      { id: "7a", es: "Plomería, calefacción & electricidad (Gasfitería)", en: "Plumbing, heating & electricity" },
      { id: "7b", es: "Carpintería, pintura, albañilería & cerrajería", en: "Carpentry, painting, masonry & locksmithing" },
      { id: "7c", es: "Reparación de electrodomésticos, smartphones & computadoras", en: "Appliance, smartphone & computer repair" },
      { id: "7d", es: "Diversos obras, renovación & mantenimiento", en: "Various construction, renovation & maintenance" },
    ],
  },
  {
    id: 8,
    emoji: "🏠",
    slug: "servicios-domesticos",
    es: "Servicios Domésticos & Ayuda Personal",
    en: "Domestic Services & Personal Assistance",
    color: "#EC4899",
    subcategories: [
      { id: "8a", es: "Limpieza, orden & lavandería", en: "Cleaning, tidying & laundry" },
      { id: "8b", es: "Cuidado de niños, babysitters bilingües & niñeras", en: "Child care, bilingual babysitters & nannies" },
      { id: "8c", es: "Jardinería, espacios verdes & guardianía", en: "Gardening, green spaces & caretaking" },
      { id: "8d", es: "Diversos servicios a domicilio & asistencia diaria", en: "Various home services & daily assistance" },
    ],
  },
  {
    id: 9,
    emoji: "💻",
    slug: "tecnologia",
    es: "Tecnología, Informática & Digital",
    en: "Technology, IT & Digital",
    color: "#06B6D4",
    subcategories: [
      { id: "9a", es: "Soporte informático, redes & wifi doméstico", en: "IT support, networks & home wifi" },
      { id: "9b", es: "Creación de sitios web, programación & mantenimiento", en: "Web creation, programming & maintenance" },
      { id: "9c", es: "Diseño gráfico, contenido & marketing digital", en: "Graphic design, content & digital marketing" },
      { id: "9d", es: "Diversos informática, tech & asistencia digital", en: "Various IT, tech & digital assistance" },
    ],
  },
  {
    id: 10,
    emoji: "💅",
    slug: "belleza",
    es: "Belleza, Estética & Cuidado Personal",
    en: "Beauty, Aesthetics & Personal Care",
    color: "#F472B6",
    subcategories: [
      { id: "10a", es: "Peluquería & barbería (en salón o a domicilio)", en: "Hairdressing & barbershop (salon or home)" },
      { id: "10b", es: "Manicura, pedicura & depilación", en: "Manicure, pedicure & hair removal" },
      { id: "10c", es: "Cuidado facial, cosmética & dermatología estética", en: "Facial care, cosmetics & aesthetic dermatology" },
      { id: "10d", es: "Diversos belleza, estética & bienestar corporal", en: "Various beauty, aesthetics & body wellness" },
    ],
  },
  {
    id: 11,
    emoji: "🐾",
    slug: "animales",
    es: "Animales & Servicios Veterinarios",
    en: "Animals & Veterinary Services",
    color: "#84CC16",
    subcategories: [
      { id: "11a", es: "Veterinarios (en clínica o a domicilio)", en: "Veterinarians (clinic or home)" },
      { id: "11b", es: "Cuidado de animales, pensiones & paseos (Dog-walking)", en: "Pet care, boarding & dog-walking" },
      { id: "11c", es: "Peluquería canina, higiene & cuidados animales", en: "Pet grooming, hygiene & animal care" },
      { id: "11d", es: "Diversos animales, adiestramiento canino & accesorios", en: "Various animals, dog training & accessories" },
    ],
  },
  {
    id: 12,
    emoji: "🎓",
    slug: "educacion",
    es: "Educación, Idiomas & Artes Vivas",
    en: "Education, Languages & Living Arts",
    color: "#7C3AED",
    subcategories: [
      { id: "12a", es: "Clases de Idiomas (Español, Quechua, Inglés, Francés, intercambios)", en: "Language courses (Spanish, Quechua, English, French, exchanges)" },
      { id: "12b", es: "Clases de Danza (Salsa, Bachata, danzas tradicionales andinas)", en: "Dance classes (Salsa, Bachata, Andean traditional dances)" },
      { id: "12c", es: "Música & Canto (Guitarra, Charango, Flautas andinas, percusión, voz)", en: "Music & Singing (Guitar, Charango, Andean flutes, drums, voice)" },
      { id: "12d", es: "Diversos Educación, apoyo académico & talleres de arte", en: "Various Education, academic tutoring & art workshops" },
    ],
  },
  {
    id: 13,
    emoji: "⚖️",
    slug: "administracion",
    es: "Administración, Legal & Traducción",
    en: "Administration, Legal & Translation",
    color: "#1E40AF",
    subcategories: [
      { id: "13a", es: "Traducciones certificadas & interpretariado", en: "Certified translations & interpreting" },
      { id: "13b", es: "Asesoría jurídica, abogados & trámites de inmigración (Migraciones)", en: "Legal advice, lawyers & immigration services" },
      { id: "13c", es: "Contabilidad, gestión administrativa & impuestos (SUNAT)", en: "Accounting, administration & taxes (SUNAT)" },
      { id: "13d", es: "Diversos servicios administrativos, legales & oficiales", en: "Various administrative, legal & official services" },
    ],
  },
  {
    id: 14,
    emoji: "🗺️",
    slug: "turismo",
    es: "Turismo, Excursiones & Guías",
    en: "Tourism, Excursions & Guides",
    color: "#059669",
    subcategories: [
      { id: "14a", es: "Guías turísticos certificados (bilingüe/multilingüe)", en: "Certified tour guides (bilingual/multilingual)" },
      { id: "14b", es: "Agencias locales, reservas (Machu Picchu, trenes) & treks", en: "Local agencies, bookings (Machu Picchu, trains) & treks" },
      { id: "14c", es: "Alquiler & venta de material de senderismo y camping", en: "Rental & sale of hiking and camping gear" },
      { id: "14d", es: "Diversos turismo, logística de viaje & excursiones", en: "Various tourism, travel logistics & excursions" },
    ],
  },
  {
    id: 15,
    emoji: "🎨",
    slug: "experiencias",
    es: "Experiencias Únicas & Culturales",
    en: "Unique & Cultural Experiences",
    color: "#D97706",
    subcategories: [
      { id: "15a", es: "Talleres de artesanía (tejido, cerámica, joyería)", en: "Craft workshops (weaving, pottery, jewelry)" },
      { id: "15b", es: "Cenas clandestinas, astronomía andina & eventos exclusivos", en: "Clandestine dinners, Andean astronomy & exclusive events" },
      { id: "15c", es: "Safari fotográfico & inmersiones en comunidades locales", en: "Photo safaris & immersions in local communities" },
      { id: "15d", es: "Diversos experiencias insólitas & micro-aventuras", en: "Various unusual experiences & micro-adventures" },
    ],
  },
  {
    id: 16,
    emoji: "🎭",
    slug: "eventos",
    es: "Eventos, Arte & Espectáculos",
    en: "Events, Art & Performances",
    color: "#DC2626",
    subcategories: [
      { id: "16a", es: "Fotógrafos & videógrafos profesionales (bodas, treks, retratos)", en: "Professional photographers & videographers (weddings, treks, portraits)" },
      { id: "16b", es: "Músicos, DJ, grupos en vivo & animadores de fiestas", en: "Musicians, DJs, live bands & party entertainers" },
      { id: "16c", es: "Alquiler de material para eventos (sonido, luces, carpas, mobiliario)", en: "Event equipment rental (sound, lights, tents, furniture)" },
      { id: "16d", es: "Diversos eventos, artistas, espectáculos & performances callejeras", en: "Various events, artists, shows & street performances" },
    ],
  },
];
